services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api:latest
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: web:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:3001
    depends_on:
      - backend

networks:
  default:
    name: myapp-network
    driver: bridge
